// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZiARWEuLvpUI-iYo6MOpZghXEtDZhtQ',
    appId: '1:1061772049065:web:ee302b547b51d3ec6047b8',
    messagingSenderId: '1061772049065',
    projectId: 'gsg-firebase-project',
    authDomain: 'gsg-firebase-project.firebaseapp.com',
    storageBucket: 'gsg-firebase-project.appspot.com',
    measurementId: 'G-HJKNKX13VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClt5aJGTK_HOSNlyLHj4cioXw3IaFtjKY',
    appId: '1:1061772049065:android:cf5b2ce076737b8e6047b8',
    messagingSenderId: '1061772049065',
    projectId: 'gsg-firebase-project',
    storageBucket: 'gsg-firebase-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo6tZJVXOZ_R_T3AYa2BZl1fiDto_8blY',
    appId: '1:1061772049065:ios:3a9e356686bddb0c6047b8',
    messagingSenderId: '1061772049065',
    projectId: 'gsg-firebase-project',
    storageBucket: 'gsg-firebase-project.appspot.com',
    iosClientId: '1061772049065-qjqss6oua4f2v44tmd11tcst4i2hm6el.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseAppTest',
  );
}
